version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    container_name: server
    build:
      context: .
      args:
        LOCAL: "true"
    environment:
      STORAGE_MODE: "${STORAGE_MODE}"
      TRANSPORT_MODE: "${TRANSPORT_MODE}"
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres

volumes:
  postgres-db:
